### ISSUE TITLE
On Cygwin: sys/ptrace.h: No such file or directory

### ISSUE THREAD

**Issue by g-reno** [existz/shc-3.8.9#2]
On latest version of Cygwin:

~/shc/shc-3.8.9
$ make test
**\*     Compiling script "match"
CFLAGS="-Wall " ./shc -v -f match
shc shll=sh
shc [-i]=-c
shc [-x]=exec '%s' "$@"
shc [-l]=
shc opts=
shc: cc -Wall  match.x.c -o match.x
match.x.c:260:24: fatal error: sys/ptrace.h: No such file or directory
 #include <sys/ptrace.h>
                        ^
compilation terminated.
./shc: No error
makefile:43: recipe for target 'match.x' failed
# make: \* \* \* [match.x] Error 1

How do we solve this?

**Comment by g-reno** [comment]
So I try to remove all references to ptrace, but then the executeable behaves strangely:

$ ./match.x
./match.x: No such file or directory
Killed

$ ls -l
total 186
-rw-r----- 1 Administrator None  3846 May  7  2012 CHANGES
-rw-r----- 1 Administrator None 17982 May  9  1996 Copying
-rw-r----- 1 Administrator None  1941 Apr 28  2012 makefile
-rwxr-x--- 1 Administrator None   336 Feb 21  2003 match
-rwx--x--x 1 Administrator None 10766 Dec 15 21:29 match.x
-rw-r--r-- 1 Administrator None 11166 Dec 15 21:29 match.x.c
-rwxr-x--- 1 Administrator None   155 Jun 19  2003 pru.sh
-rw-r----- 1 Administrator None  3136 Jul  8  2004 shc.1
lrwxrwxrwx 1 Administrator None    11 Dec  4 05:21 shc.c -> shc-3.8.9.c
-rwxr-xr-x 1 Administrator None 85922 Dec 15 21:29 shc.exe
-rw-r----- 1 Administrator None  4558 Jul  8  2004 shc.html
-rw-r----- 1 Administrator None  1544 Jun 19  2003 shc.README
-rw-r----- 1 Administrator None 24948 Dec 15 21:28 shc-3.8.9.c
-rwxr-x--- 1 Administrator None   138 Nov 12  2004 test.bash
-rwxr-x--- 1 Administrator None    52 Jun 19  2003 test.csh
-rwxr-x--- 1 Administrator None   142 Jan 18  2008 test.ksh

The file match.x has the proper permissions but it refuses to run.

**Comment by existz** [comment]
I believe this is the same as issue #1 . A possible fix was pushed and once verified the issue will be closed.

**Comment by existz** [comment]
Closing this issue as well, a recent fix was pushed and verified.
